server:
  port: 8888

spring:
  datasource:
    password: 'root'
    url: jdbc:hsqldb:mem:testdb
    username: SA
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    sql-script-encoding: UTF-8
    initialization-mode: always
#  main:
#    banner-mode: 'off'

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate.format_sql: true


