spring:
  datasource:
    password: 'root'
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: SA
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate.format_sql: true


