
CREATE TABLE doc_type (
                          id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
                          name VARCHAR(50) NOT NULL,
                          code VARCHAR(20) NOT NULL
);

CREATE TABLE country (
                         id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
                         name VARCHAR(50) NOT NULL,
                         code VARCHAR(20) NOT NULL
);

CREATE TABLE organization(
                             id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
                             name VARCHAR(50) NOT NULL,
                             full_name VARCHAR(100)NOT NULL,
                             inn VARCHAR(12) NOT NULL,
                             kpp VARCHAR(9) NOT NULL,
                             address VARCHAR(200)NOT NULL,
                             phone VARCHAR(20),
                             is_active BOOLEAN NOT NULL
);

CREATE TABLE office (
                        id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
                        org_id INTEGER NOT NULL REFERENCES organization(id),
                        name VARCHAR(50) NOT NULL,
                        address VARCHAR(200) NOT NULL,
                        phone VARCHAR(20),
                        is_active BOOLEAN NOT NULL
);


CREATE TABLE user(
                     id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
                     office_id INTEGER NOT NULL REFERENCES office(id),
                     country_id INTEGER NOT NULL REFERENCES country(id),
                     second_name VARCHAR(50) NOT NULL,
                     first_name VARCHAR(50) NOT NULL,
                     middle_name VARCHAR(50),
                     position VARCHAR(50) NOT NULL,
                     phone VARCHAR(20),
                     is_identified BOOLEAN NOT NULL
);


CREATE TABLE doc (
                     id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY REFERENCES user(id),
                     doc_type_id INTEGER NOT NULL REFERENCES doc_type(id),
                     number VARCHAR(50) NOT NULL,
                     date DATE NOT NULL
);
